version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    assignees:
      - hizumiaoba
    schedule:
      interval: "weekly"
    groups:
      gradle-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - hizumiaoba
    schedule:
      interval: "weekly"

